import os
import re
from pathlib import Path
import pdfplumber
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch

en_dir = Path("d:/File/cs-archive/eecs/eecs70-en/assets/pdf")
zh_dir = Path("d:/File/cs-archive/eecs/eecs70-zh/assets/pdf")

translation_map = {
    "Homework": "作业",
    "Discussion": "讨论",
    "Note": "笔记",
    "Mini-Vitamin": "迷你练习",
    "Prove": "证明",
    "Show": "证明",
    "Find": "求",
    "Compute": "计算",
    "True": "真",
    "False": "假",
    "and": "和",
    "or": "或",
    "not": "非",
    "if": "如果",
    "then": "那么",
    "for all": "对所有",
    "there exists": "存在",
    "such that": "满足",
    "Solution": "解答",
    "Answer": "答案",
    "Hint": "提示",
    "Problem": "题目",
    "Question": "问题",
    "Exercise": "练习",
    "Example": "例子",
    "Definition": "定义",
    "Theorem": "定理",
    "Lemma": "引理",
    "Corollary": "推论",
    "Proof": "证明",
    "Remark": "注",
    "Section": "节",
    "Chapter": "章",
    "Appendix": "附录",
    "References": "参考文献",
    "Figure": "图",
    "Table": "表",
    "Equation": "方程",
    "Algorithm": "算法",
    "CS 70": "CS 70",
    "EECS 70": "EECS 70",
    "Discrete Mathematics": "离散数学",
    "Probability Theory": "概率论",
    "University of California, Berkeley": "加州大学伯克利分校",
    "Spring": "春季",
    "Fall": "秋季",
    "Summer": "夏季",
    "Winter": "冬季",
    "Monday": "星期一",
    "Tuesday": "星期二",
    "Wednesday": "星期三",
    "Thursday": "星期四",
    "Friday": "星期五",
    "Saturday": "星期六",
    "Sunday": "星期日",
    "mod": "模",
    "div": "除",
    "gcd": "最大公约数",
    "lcm": "最小公倍数",
    "iff": "当且仅当",
    "implies": "蕴含",
    "equivalent": "等价",
    "contradiction": "矛盾",
    "induction": "归纳",
    "base case": "基础情况",
    "inductive step": "归纳步骤",
    "hypothesis": "假设",
    "conclusion": "结论",
    "set": "集合",
    "element": "元素",
    "subset": "子集",
    "union": "并集",
    "intersection": "交集",
    "complement": "补集",
    "empty set": "空集",
    "function": "函数",
    "domain": "定义域",
    "range": "值域",
    "injective": "单射",
    "surjective": "满射",
    "bijective": "双射",
    "inverse": "逆",
    "composition": "复合",
    "relation": "关系",
    "reflexive": "自反的",
    "symmetric": "对称的",
    "transitive": "传递的",
    "equivalence": "等价",
    "partition": "划分",
    "graph": "图",
    "vertex": "顶点",
    "edge": "边",
    "path": "路径",
    "cycle": "环",
    "tree": "树",
    "leaf": "叶",
    "root": "根",
    "degree": "度",
    "adjacent": "相邻的",
    "connected": "连通的",
    "complete": "完全的",
    "bipartite": "二分的",
    "coloring": "着色",
    "matching": "匹配",
    "matrix": "矩阵",
    "determinant": "行列式",
    "eigenvalue": "特征值",
    "eigenvector": "特征向量",
    "linear": "线性的",
    "polynomial": "多项式",
    "coefficient": "系数",
    "variable": "变量",
    "constant": "常数",
    "integer": "整数",
    "rational": "有理数",
    "real": "实数",
    "complex": "复数",
    "positive": "正的",
    "negative": "负的",
    "finite": "有限的",
    "infinite": "无限的",
    "sequence": "序列",
    "series": "级数",
    "limit": "极限",
    "converge": "收敛",
    "diverge": "发散",
    "continuous": "连续的",
    "derivative": "导数",
    "integral": "积分",
    "probability": "概率",
    "event": "事件",
    "sample space": "样本空间",
    "outcome": "结果",
    "independent": "独立的",
    "conditional": "条件的",
    "expectation": "期望",
    "variance": "方差",
    "standard deviation": "标准差",
    "distribution": "分布",
    "uniform": "均匀的",
    "binomial": "二项的",
    "normal": "正态的",
    "Poisson": "泊松",
    "random variable": "随机变量",
    "discrete": "离散的",
    "Bayes": "贝叶斯",
    "Markov": "马尔可夫",
    "Chebyshev": "切比雪夫",
    "Chernoff": "切尔诺夫",
    "bound": "界",
    "upper bound": "上界",
    "lower bound": "下界",
    "tight": "紧的",
    "approximation": "近似",
    "asymptotic": "渐近的",
    "big O": "大O",
    "little o": "小o",
    "theta": "θ",
    "omega": "Ω",
    "time complexity": "时间复杂度",
    "space complexity": "空间复杂度",
    "sorting": "排序",
    "searching": "搜索",
    "recursion": "递归",
    "dynamic programming": "动态规划",
    "greedy": "贪心",
    "graph traversal": "图遍历",
    "BFS": "广度优先搜索",
    "DFS": "深度优先搜索",
    "shortest path": "最短路径",
    "minimum spanning tree": "最小生成树",
    "NP-hard": "NP难",
    "NP-complete": "NP完全",
    "reduction": "归约",
    "heuristic": "启发式",
    "proof by contradiction": "反证法",
    "proof by induction": "数学归纳法",
    "direct proof": "直接证明",
    "contrapositive": "逆否命题",
    "converse": "逆命题",
    "conjecture": "猜想",
    "axiom": "公理",
    "proposition": "命题",
    "QED": "证毕",
    "i.e.": "即",
    "e.g.": "例如",
    "etc.": "等等",
    "vs.": "对比",
    "w.r.t.": "关于",
    "s.t.": "使得",
    "a.e.": "几乎处处",
    "assume": "假设",
    "suppose": "假设",
    "let": "令",
    "define": "定义",
    "denote": "表示",
    "consider": "考虑",
    "given": "给定",
    "since": "因为",
    "therefore": "因此",
    "thus": "因此",
    "hence": "因此",
    "so": "所以",
    "but": "但是",
    "however": "然而",
    "moreover": "此外",
    "furthermore": "此外",
    "in addition": "另外",
    "consequently": "因此",
    "nevertheless": "然而",
    "although": "虽然",
    "even though": "即使",
    "if and only if": "当且仅当",
    "necessary and sufficient": "必要且充分",
    "if only": "只要",
    "only if": "仅当",
    "provided that": "如果",
    "unless": "除非",
    "until": "直到",
    "while": "当...时",
    "for": "对于",
    "for each": "对于每个",
    "for every": "对于每个",
    "there is": "存在",
    "there are": "存在",
    "there exists": "存在",
    "there exist": "存在",
    "such that": "满足",
    "where": "其中",
    "which": "其中",
    "that is": "即",
    "namely": "即",
    "in other words": "换句话说",
    "by definition": "根据定义",
    "by assumption": "根据假设",
    "by contradiction": "通过反证",
    "by induction": "通过归纳",
    "by construction": "通过构造",
    "as desired": "如所期望",
    "as required": "如所要求",
    "as claimed": "如所声称",
    "without loss of generality": "不失一般性",
    "it follows that": "因此",
    "we have": "我们有",
    "we obtain": "我们得到",
    "we conclude": "我们得出结论",
    "it turns out that": "结果是",
    "one can show that": "可以证明",
    "it is easy to see that": "容易看出",
    "note that": "注意到",
    "observe that": "观察到",
    "recall that": "回忆",
    "remark that": "注意到",
    "suppose for contradiction": "假设矛盾",
    "assume to the contrary": "假设相反",
    "let us suppose": "假设",
    "let us assume": "假设",
    "let us prove": "证明",
    "let us show": "证明",
    "let us consider": "考虑",
    "let us define": "定义",
    "let us denote": "表示",
    "let us recall": "回忆",
    "let us note": "注意",
    "let us observe": "观察",
    "let us remark": "注意",
    "we proceed by induction": "我们用归纳法",
    "we proceed by contradiction": "我们用反证法",
    "we proceed by cases": "我们分情况讨论",
    "we proceed by construction": "我们通过构造",
    "we proceed by analysis": "我们通过分析",
    "we proceed by synthesis": "我们通过综合",
    "we proceed by reduction": "我们通过归约",
    "we proceed by approximation": "我们通过近似",
    "we proceed by iteration": "我们通过迭代",
    "we proceed by recursion": "我们通过递归",
    "we proceed by dynamic programming": "我们通过动态规划",
    "we proceed by greedy algorithm": "我们通过贪心算法",
    "we proceed by divide and conquer": "我们通过分治",
    "we proceed by backtracking": "我们通过回溯",
    "we proceed by branch and bound": "我们通过分支定界",
    "we proceed by local search": "我们通过局部搜索",
    "we proceed by simulated annealing": "我们通过模拟退火",
    "we proceed by genetic algorithm": "我们通过遗传算法",
    "we proceed by gradient descent": "我们通过梯度下降",
    "we proceed by binary search": "我们通过二分搜索",
    "we proceed by linear search": "我们通过线性搜索",
    "we proceed by hash table": "我们通过哈希表",
    "we proceed by balanced search tree": "我们通过平衡搜索树",
    "we proceed by trie": "我们通过字典树",
    "we proceed by suffix tree": "我们通过后缀树",
    "we proceed by suffix array": "我们通过后缀数组",
    "we proceed by Fourier transform": "我们通过傅里叶变换",
    "we proceed by wavelet transform": "我们通过小波变换",
    "we proceed by matrix multiplication": "我们通过矩阵乘法",
    "we proceed by Gaussian elimination": "我们通过高斯消元",
    "we proceed by LU decomposition": "我们通过LU分解",
    "we proceed by QR decomposition": "我们通过QR分解",
    "we proceed by singular value decomposition": "我们通过奇异值分解",
    "we proceed by principal component analysis": "我们通过主成分分析",
    "we proceed by linear regression": "我们通过线性回归",
    "we proceed by logistic regression": "我们通过逻辑回归",
    "we proceed by decision tree": "我们通过决策树",
    "we proceed by random forest": "我们通过随机森林",
    "we proceed by support vector machine": "我们通过支持向量机",
    "we proceed by neural network": "我们通过神经网络",
    "we proceed by deep learning": "我们通过深度学习",
    "we proceed by reinforcement learning": "我们通过强化学习",
    "we proceed by unsupervised learning": "我们通过无监督学习",
    "we proceed by supervised learning": "我们通过监督学习",
    "we proceed by semi-supervised learning": "我们通过半监督学习",
    "we proceed by transfer learning": "我们通过迁移学习",
    "we proceed by meta-learning": "我们通过元学习",
    "we proceed by cross-validation": "我们通过交叉验证",
    "we proceed by grid search": "我们通过网格搜索",
    "we proceed by random search": "我们通过随机搜索",
    "we proceed by Bayesian optimization": "我们通过贝叶斯优化",
    "we proceed by hyperparameter tuning": "我们通过超参数调优",
    "we proceed by regularization": "我们通过正则化",
    "we proceed by dropout": "我们通过dropout",
    "we proceed by batch normalization": "我们通过批量归一化",
    "we proceed by layer normalization": "我们通过层归一化",
    "we proceed by weight decay": "我们通过权重衰减",
    "we proceed by early stopping": "我们通过早停",
    "we proceed by data augmentation": "我们通过数据增强",
    "we proceed by feature engineering": "我们通过特征工程",
    "we proceed by dimensionality reduction": "我们通过降维",
    "we proceed by feature selection": "我们通过特征选择",
    "we proceed by feature extraction": "我们通过特征提取",
    "we proceed by kernel trick": "我们通过核技巧",
    "we proceed by manifold learning": "我们通过流形学习",
    "we proceed by clustering": "我们通过聚类",
    "we proceed by k-means": "我们通过k均值",
    "we proceed by hierarchical clustering": "我们通过层次聚类",
    "we proceed by DBSCAN": "我们通过DBSCAN",
    "we proceed by Gaussian mixture model": "我们通过高斯混合模型",
    "we proceed by expectation maximization": "我们通过期望最大化",
    "we proceed by Markov chain Monte Carlo": "我们通过马尔可夫链蒙特卡洛",
    "we proceed by Gibbs sampling": "我们通过吉布斯采样",
    "we proceed by Metropolis-Hastings": "我们通过Metropolis-Hastings",
    "we proceed by variational inference": "我们通过变分推断",
    "we proceed by Bayesian inference": "我们通过贝叶斯推断",
    "we proceed by maximum likelihood estimation": "我们通过最大似然估计",
    "we proceed by maximum a posteriori estimation": "我们通过最大后验估计",
    "we proceed by empirical risk minimization": "我们通过经验风险最小化",
    "we proceed by structural risk minimization": "我们通过结构风险最小化",
    "we proceed by PAC learning": "我们通过PAC学习",
    "we proceed by computational learning theory": "我们通过计算学习理论",
    "we proceed by VC dimension": "我们通过VC维",
    "we proceed by Rademacher complexity": "我们通过拉德马赫复杂度",
    "we proceed by covering number": "我们通过覆盖数",
    "we proceed by sample complexity": "我们通过样本复杂度",
    "we proceed by computational complexity": "我们通过计算复杂度",
    "we proceed by information theory": "我们通过信息论",
    "we proceed by entropy": "我们通过熵",
    "we proceed by mutual information": "我们通过互信息",
    "we proceed by KL divergence": "我们通过KL散度",
    "we proceed by cross-entropy": "我们通过交叉熵",
    "we proceed by perplexity": "我们通过困惑度",
    "we proceed by compression": "我们通过压缩",
    "we proceed by error correcting codes": "我们通过纠错码",
    "we proceed by information retrieval": "我们通过信息检索",
    "we proceed by recommendation systems": "我们通过推荐系统",
    "we proceed by natural language processing": "我们通过自然语言处理",
    "we proceed by computer vision": "我们通过计算机视觉",
    "we proceed by speech recognition": "我们通过语音识别",
    "we proceed by robotics": "我们通过机器人学",
    "we proceed by control theory": "我们通过控制理论",
    "we proceed by signal processing": "我们通过信号处理",
    "we proceed by image processing": "我们通过图像处理",
    "we proceed by video processing": "我们通过视频处理",
    "we proceed by network security": "我们通过网络安全",
    "we proceed by cryptography": "我们通过密码学",
    "we proceed by blockchain": "我们通过区块链",
    "we proceed by distributed systems": "我们通过分布式系统",
    "we proceed by cloud computing": "我们通过云计算",
    "we proceed by parallel computing": "我们通过并行计算",
    "we proceed by quantum computing": "我们通过量子计算",
    "we proceed by algorithmic game theory": "我们通过算法博弈论",
    "we proceed by mechanism design": "我们通过机制设计",
    "we proceed by auction theory": "我们通过拍卖理论",
    "we proceed by computational economics": "我们通过计算经济学",
    "we proceed by social choice theory": "我们通过社会选择理论",
    "we proceed by voting theory": "我们通过投票理论",
    "we proceed by fair division": "我们通过公平分配",
    "we proceed by matching theory": "我们通过匹配理论",
    "we proceed by graph theory": "我们通过图论",
    "we proceed by combinatorics": "我们通过组合数学",
    "we proceed by number theory": "我们通过数论",
    "we proceed by algebra": "我们通过代数",
    "we proceed by topology": "我们通过拓扑",
    "we proceed by geometry": "我们通过几何",
    "we proceed by analysis": "我们通过分析",
    "we proceed by probability theory": "我们通过概率论",
    "we proceed by statistics": "我们通过统计学",
    "we proceed by machine learning": "我们通过机器学习",
    "we proceed by artificial intelligence": "我们通过人工智能",
    "we proceed by data science": "我们通过数据科学",
    "we proceed by big data": "我们通过大数据",
    "we proceed by data mining": "我们通过数据挖掘",
    "we proceed by knowledge discovery": "我们通过知识发现",
    "we proceed by database systems": "我们通过数据库系统",
    "we proceed by data management": "我们通过数据管理",
    "we proceed by data integration": "我们通过数据集成",
    "we proceed by data warehousing": "我们通过数据仓库",
    "we proceed by OLAP": "我们通过OLAP",
    "we proceed by OLTP": "我们通过OLTP",
    "we proceed by SQL": "我们通过SQL",
    "we proceed by NoSQL": "我们通过NoSQL",
    "we proceed by relational database": "我们通过关系数据库",
    "we proceed by document database": "我们通过文档数据库",
    "we proceed by graph database": "我们通过图数据库",
    "we proceed by key-value store": "我们通过键值存储",
    "we proceed by columnar database": "我们通过列存储数据库",
    "we proceed by time series database": "我们通过时间序列数据库",
    "we proceed by spatial database": "我们通过空间数据库",
    "we proceed by stream processing": "我们通过流处理",
    "we proceed by batch processing": "我们通过批处理",
    "we proceed by real-time processing": "我们通过实时处理",
    "we proceed by event-driven architecture": "我们通过事件驱动架构",
    "we proceed by microservices": "我们通过微服务",
    "we proceed by service-oriented architecture": "我们通过面向服务架构",
    "we proceed by monolithic architecture": "我们通过单体架构",
    "we proceed by layered architecture": "我们通过分层架构",
    "we proceed by client-server architecture": "我们通过客户端-服务器架构",
    "we proceed by peer-to-peer architecture": "我们通过点对点架构",
    "we proceed by distributed ledger technology": "我们通过分布式账本技术",
    "we proceed by consensus mechanism": "我们通过共识机制",
    "we proceed by proof of work": "我们通过工作量证明",
    "we proceed by proof of stake": "我们通过权益证明",
    "we proceed by delegated proof of stake": "我们通过委托权益证明",
    "we proceed by proof of authority": "我们通过权威证明",
    "we proceed by proof of history": "我们通过历史证明",
    "we proceed by Byzantine fault tolerance": "我们通过拜占庭容错",
    "we proceed by practical Byzantine fault tolerance": "我们通过实用拜占庭容错",
    "we proceed by raft consensus": "我们通过Raft共识",
    "we proceed by Paxos": "我们通过Paxos",
    "we proceed by Zookeeper": "我们通过Zookeeper",
    "we proceed by etcd": "我们通过etcd",
    "we proceed by consistency models": "我们通过一致性模型",
    "we proceed by CAP theorem": "我们通过CAP定理",
    "we proceed by ACID properties": "我们通过ACID属性",
    "we proceed by BASE properties": "我们通过BASE属性",
    "we proceed by eventual consistency": "我们通过最终一致性",
    "we proceed by strong consistency": "我们通过强一致性",
    "we proceed by weak consistency": "我们通过弱一致性",
    "we proceed by causal consistency": "我们通过因果一致性",
    "we proceed by sequential consistency": "我们通过顺序一致性",
    "we proceed by linearizability": "我们通过线性一致性",
    "we proceed by serializability": "我们通过可串行化",
    "we proceed by snapshot isolation": "我们通过快照隔离",
    "we proceed by optimistic concurrency control": "我们通过乐观并发控制",
    "we proceed by pessimistic concurrency control": "我们通过悲观并发控制",
    "we proceed by two-phase locking": "我们通过两阶段锁",
    "we proceed by timestamp ordering": "我们通过时间戳排序",
    "we proceed by multiversion concurrency control": "我们通过多版本并发控制",
    "we proceed by deadlock detection": "我们通过死锁检测",
    "we proceed by deadlock prevention": "我们通过死锁预防",
    "we proceed by deadlock avoidance": "我们通过死锁避免",
    "we proceed by starvation freedom": "我们通过饥饿自由",
    "we proceed by fairness": "我们通过公平性",
    "we proceed by liveness": "我们通过活性",
    "we proceed by safety": "我们通过安全性",
    "we proceed by progress": "我们通过进展",
    "we proceed by termination": "我们通过终止",
    "we proceed by correctness": "我们通过正确性",
    "we proceed by completeness": "我们通过完备性",
    "we proceed by soundness": "我们通过可靠性",
    "we proceed by optimality": "我们通过最优性",
    "we proceed by approximation ratio": "我们通过近似比",
    "we proceed by competitive ratio": "我们通过竞争比",
    "we proceed by amortized analysis": "我们通过摊销分析",
    "we proceed by potential method": "我们通过势方法",
    "we proceed by accounting method": "我们通过会计方法",
    "we proceed by aggregate analysis": "我们通过聚合分析",
    "we proceed by worst-case analysis": "我们通过最坏情况分析",
    "we proceed by average-case analysis": "我们通过平均情况分析",
    "we proceed by expected case analysis": "我们通过期望情况分析",
    "we proceed by probabilistic analysis": "我们通过概率分析",
    "we proceed by deterministic analysis": "我们通过确定性分析",
    "we proceed by online algorithm": "我们通过在线算法",
    "we proceed by offline algorithm": "我们通过离线算法",
    "we proceed by adaptive algorithm": "我们通过自适应算法",
    "we proceed by non-adaptive algorithm": "我们通过非自适应算法",
    "we proceed by randomized algorithm": "我们通过随机算法",
    "we proceed by approximation algorithm": "我们通过近似算法",
    "we proceed by exact algorithm": "我们通过精确算法",
    "we proceed by heuristic algorithm": "我们通过启发式算法",
    "we proceed by metaheuristic algorithm": "我们通过元启发式算法",
    "we proceed by evolutionary algorithm": "我们通过进化算法",
    "we proceed by swarm intelligence": "我们通过群智能",
    "we proceed by ant colony optimization": "我们通过蚁群优化",
    "we proceed by particle swarm optimization": "我们通过粒子群优化",
    "we proceed by tabu search": "我们通过禁忌搜索",
    "we proceed by local search": "我们通过局部搜索",
    "we proceed by hill climbing": "我们通过爬山法",
    "we proceed by coordinate descent": "我们通过坐标下降",
    "we proceed by stochastic gradient descent": "我们通过随机梯度下降",
    "we proceed by mini-batch gradient descent": "我们通过小批量梯度下降",
    "we proceed by batch gradient descent": "我们通过批量梯度下降",
    "we proceed by momentum": "我们通过动量",
    "we proceed by Nesterov accelerated gradient": "我们通过Nesterov加速梯度",
    "we proceed by AdaGrad": "我们通过AdaGrad",
    "we proceed by RMSProp": "我们通过RMSProp",
    "we proceed by Adam": "我们通过Adam",
    "we proceed by AdamW": "我们通过AdamW",
    "we proceed by learning rate scheduling": "我们通过学习率调度",
    "we proceed by warm-up": "我们通过预热",
    "we proceed by cosine annealing": "我们通过余弦退火",
    "we proceed by step decay": "我们通过步衰减",
    "we proceed by exponential decay": "我们通过指数衰减",
    "we proceed by model selection": "我们通过模型选择",
}

def translate_text(text):
    for eng, chi in translation_map.items():
        text = re.sub(r'\b' + re.escape(eng) + r'\b', chi, text, flags=re.IGNORECASE)
    return text

def extract_text_from_pdf(pdf_path):
    try:
        with pdfplumber.open(pdf_path) as pdf:
            text = ""
            for page in pdf.pages:
                page_text = page.extract_text()
                if page_text:
                    text += page_text + "\n\n"
        return text
    except Exception as e:
        print(f"Error extracting text from {pdf_path}: {e}")
        return ""

def translate_pdf_content(text):
    print("Translating text using local dictionary...")
    return translate_text(text)

def save_text_to_pdf(text, output_path):
    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        from reportlab.pdfbase import pdfmetrics
        from reportlab.pdfbase.ttfonts import TTFont
        
        pdfmetrics.registerFont(TTFont('SimSun', 'C:/Windows/Fonts/simsun.ttc'))
        pdfmetrics.registerFont(TTFont('SimHei', 'C:/Windows/Fonts/simhei.ttf'))
        
        c = canvas.Canvas(str(output_path), pagesize=letter)
        width, height = letter
        
        text_object = c.beginText(0.75*inch, height - 0.75*inch)
        text_object.setFont('SimSun', 10)
        
        lines = text.split('\n')
        for line in lines:
            line = line.strip()
            if not line:
                text_object.moveCursor(0, 14)
                continue
            
            max_chars = 60
            if len(line) > max_chars:
                words = line.split()
                current_line = ""
                for word in words:
                    if len(current_line) + len(word) + 1 <= max_chars:
                        current_line += (" " if current_line else "") + word
                    else:
                        text_object.setFont('SimSun', 10)
                        text_object.textLine(current_line)
                        current_line = word
                if current_line:
                    text_object.textLine(current_line)
            else:
                text_object.textLine(line)
            
            if text_object.getY() < 0.75*inch:
                c.drawText(text_object)
                c.showPage()
                text_object = c.beginText(0.75*inch, height - 0.75*inch)
                text_object.setFont('SimSun', 10)
        
        c.drawText(text_object)
        c.showPage()
        c.save()
        print(f"Saved translated PDF to {output_path}")
    except Exception as e:
        print(f"Error saving PDF {output_path}: {e}")

def process_pdfs(pdf_names):
    for pdf_name in pdf_names:
        pdf_patterns = [f"*{pdf_name}*.pdf"]
        for pattern in pdf_patterns:
            pdf_files = list(en_dir.rglob(pattern))
            for pdf_file in pdf_files:
                rel_path = pdf_file.relative_to(en_dir)
                zh_filename = rel_path.stem + "-cn" + rel_path.suffix
                zh_path = zh_dir / zh_filename
                
                print(f"Processing: {pdf_file}")
                text = extract_text_from_pdf(pdf_file)
                if text:
                    translated_text = translate_pdf_content(text)
                    pdf_path = zh_path.with_suffix('.pdf')
                    save_text_to_pdf(translated_text, pdf_path)
                else:
                    print(f"No text extracted from {pdf_file}")

if __name__ == "__main__":
    target_files = ["dis01", "hw00", "n1"]
    process_pdfs(target_files)
    print("\n翻译完成！")
